export const categories = [
  "agricultura",
  "agua",
  "alimentos y bebidas",
  "automotriz",
  "belleza",
  "comunicaciones",
  "construcción",
  "cursos",
  "deportes",
  "educación",
  "energía",
  "entretenimiento",
  "financiero",
  "ganadería",
  "hogar",
  "inmobiliario",
  "mantenimiento y reparaciones",
  "minería",
  "moda",
  "pesca",
  "restaurantero",
  "salud",
  "servicios profesionales",
  "tecnología",
  "transporte",
  "turístico",
  "venta mayorista",
  "venta minorista",
  "otro",
];
